import { FieldSpec, TableConfig } from "../types";
import { generateRandomStrings } from "../utils";

// Base configuration shared across all tables
export const BASE_CONFIG = {
  catalog: process.env.TRINO_CATALOG ?? "iceberg",
  schema: process.env.TRINO_SCHEMA ?? "lab",
  format: "PARQUET" as const,
  sorted_by: ["id", "created_at"],
  partitioning: ["id"],
  idColumn: "id",
  //   tableProperties: {
  //     "write.target-file-size-bytes": 512 * 1024 * 1024, // 512 MB
  //   },
};

const narrowColumns: Record<string, FieldSpec> = {
  id: { kind: "bigint", min: 1, max: 1, nullable: 0 },
  user_name: { kind: "string", length: 16, nullable: 0 },
  amount: { kind: "double", min: 0, max: 10000, nullable: 0.05 },
  created_at: {
    kind: "monotonic_timestamp",
    start: "2024-01-01",
    end: "2025-01-01",
    nullable: 0,
  },
  status: {
    kind: "enum",
    base: "string",
    values: ["new", "paid", "delivered", "canceled"],
    nullable: 0,
  },
  country: {
    kind: "enum",
    base: "string",
    values: ["KZ", "US", "DE", "TR", "PL"],
    nullable: 0.02,
  },
  age: { kind: "int", min: 18, max: 78, nullable: 0.03 },
  note: { kind: "string", length: 8, nullable: 0.1 },
  tags: {
    kind: "array",
    element: {
      kind: "enum",
      base: "string",
      values: ["alpha", "beta", "gamma", "delta"],
    },
    minLen: 1,
    maxLen: 3,
    nullable: 0.1,
  },
};

// Array of table configurations
export const TABLE_CONFIGS: TableConfig[] = [
  {
    ...BASE_CONFIG,
    tableBase: "narrow",
    totalRows: [
      // 1_000_000,
      // 10_000_000,
      100_000_000, 1_000_000_000,
    ],
    batchRows: 1_000_000,
    enabled: true,
    // enabled: false,
    columns: narrowColumns,
  },
  {
    ...BASE_CONFIG,
    tableBase: "wide",
    totalRows: [
      // 1_000_000,
      // 10_000_000,
      100_000_000,
      // 1_000_000_000,
    ],
    batchRows: 500_000,
    enabled: true,
    // enabled: false,
    columns: {
      id: { kind: "bigint", min: 1, max: 1, nullable: 0 },
      row_1: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_2: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_3: { kind: "string", length: 7, nullable: 0 },
      row_4: { kind: "string", length: 7, nullable: 0 },
      row_5: { kind: "string", length: 1, nullable: 0 },
      row_6: { kind: "string", length: 3, nullable: 0 },
      row_7: { kind: "string", length: 1, nullable: 0 },
      row_8: { kind: "string", length: 4, nullable: 0 },
      row_9: { kind: "int", min: 1000, max: 10000, nullable: 0.05 },
      row_10: { kind: "int", min: 1000, max: 2500, nullable: 0.03 },
      row_11: { kind: "int", min: 100, max: 250, nullable: 0.03 },
      row_12: { kind: "int", min: 1000, max: 3000, nullable: 0.03 },
      row_13: { kind: "int", min: 100, max: 300, nullable: 0.03 },
      row_14: { kind: "int", min: 100, max: 5000, nullable: 0.03 },
      row_15: { kind: "int", min: 10, max: 500, nullable: 0.03 },
      row_16: { kind: "int", min: 30, max: 100, nullable: 0.03 },
      row_17: { kind: "int", min: 3, max: 10, nullable: 0.03 },
      row_18: { kind: "int", min: 1, max: 5, nullable: 0.03 },
      row_19: { kind: "int", min: 1000, max: 2500, nullable: 0.03 },
      row_20: { kind: "int", min: 100, max: 250, nullable: 0.03 },
      row_21: { kind: "int", min: 1000, max: 3000, nullable: 0.03 },
      row_22: { kind: "int", min: 100, max: 300, nullable: 0.03 },
      row_23: { kind: "int", min: 100, max: 5000, nullable: 0.03 },
      row_24: { kind: "int", min: 10, max: 500, nullable: 0.03 },
      row_25: { kind: "int", min: 30, max: 100, nullable: 0.03 },
      row_26: { kind: "int", min: 3, max: 10, nullable: 0.03 },
      row_27: { kind: "int", min: 1, max: 5, nullable: 0.03 },
      row_28: {
        kind: "enum",
        base: "string",
        values: ["a", "b", "c", "d", "e"],
        nullable: 0,
      },
      row_29: { kind: "string", length: 8, nullable: 0 },
      row_30: { kind: "string", length: 8, nullable: 0 },
      row_31: { kind: "string", length: 13, nullable: 0 },
      row_32: { kind: "string", length: 35, nullable: 0 },
      row_33: { kind: "string", length: 1, nullable: 0 },
      row_34: { kind: "string", length: 2, nullable: 0 },
      row_35: { kind: "string", length: 1, nullable: 0 },
      row_36: { kind: "string", length: 5, nullable: 0 },
      row_37: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_38: { kind: "string", length: 14, nullable: 0 },
      row_39: { kind: "string", length: 10, nullable: 0 },
      row_40: { kind: "string", length: 14, nullable: 0 },
      row_41: { kind: "string", length: 7, nullable: 0 },
      row_42: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_43: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_44: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_45: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_46: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_47: { kind: "string", length: 8, nullable: 0 },
      row_48: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(8, 1),
        nullable: 0,
      },
      row_49: { kind: "string", length: 2, nullable: 0 },
      row_50: { kind: "string", length: 1, nullable: 0 },
      row_51: { kind: "string", length: 2, nullable: 0 },
      row_52: { kind: "string", length: 1, nullable: 0 },
      row_53: { kind: "string", length: 1, nullable: 0 },
      row_54: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(8, 1),
        nullable: 0,
      },
      row_55: { kind: "string", length: 2, nullable: 0 },
      row_56: { kind: "string", length: 3, nullable: 0 },
      row_57: { kind: "string", length: 5, nullable: 0 },
      row_58: { kind: "string", length: 5, nullable: 0 },
      row_59: { kind: "string", length: 2, nullable: 0 },
      row_60: {
        kind: "timestamp",
        start: "2024-01-01",
        end: "2025-01-01",
        nullable: 0,
      },
      row_61: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(500, 8),
        nullable: 0,
      },
      row_62: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(500, 8),
        nullable: 0,
      },
      row_63: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(500, 8),
        nullable: 0,
      },
      row_64: { kind: "string", length: 3, nullable: 0 },
      row_65: { kind: "string", length: 2, nullable: 0 },
      row_66: { kind: "string", length: 7, nullable: 0 },
      row_67: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(3, 1),
        nullable: 0,
      },
      row_68: { kind: "string", length: 12, nullable: 0 },
      row_69: { kind: "string", length: 12, nullable: 0 },
      row_70: { kind: "string", length: 12, nullable: 0 },
      row_71: { kind: "string", length: 12, nullable: 0 },
      row_72: {
        kind: "enum",
        base: "string",
        values: generateRandomStrings(3, 1),
        nullable: 0,
      },
      row_73: { kind: "string", length: 32, nullable: 0 },
      row_74: { kind: "string", length: 32, nullable: 0 },
      row_75: { kind: "string", length: 8, nullable: 0 },
      row_76: { kind: "string", length: 8, nullable: 0 },
      row_77: { kind: "string", length: 4, nullable: 0 },
      row_78: { kind: "string", length: 1, nullable: 0 },
      row_79: { kind: "string", length: 1, nullable: 0 },
      row_80: { kind: "string", length: 1, nullable: 0 },
      row_81: { kind: "string", length: 1, nullable: 0 },
      row_82: { kind: "string", length: 1, nullable: 0 },
      row_83: { kind: "string", length: 10, nullable: 0 },
      row_84: { kind: "string", length: 16, nullable: 0 },
      row_85: { kind: "string", length: 14, nullable: 0 },
      row_86: { kind: "string", length: 10, nullable: 0 },
      row_87: { kind: "string", length: 1, nullable: 0 },
      row_88: { kind: "string", length: 5, nullable: 0 },
      row_89: { kind: "string", length: 4, nullable: 0 },
      row_90: { kind: "string", length: 4, nullable: 0 },
    },
  },
];
